path: ./dataset
train: images/train
val: images/val
test: images/test

nc: 1
names: ['Bear']

roboflow:
  workspace: bear-s8vh1
  project: bear-im4km
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/bear-s8vh1/bear-im4km/dataset/1
